"""
Django settings for osr project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load Environment variables using python-dotenv library
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Additional .parent added because split into multiple files in subfolder 'settings'
BASE_DIR = Path(__file__).resolve().parent.parent.parent

#& ==================================================
#^ Available in Templates - Pass to Context Processor
#& ==================================================

APP_NAME = "RecipeBook"
APP_EMAIL = "2ravenstech@gmail.com" # This will be an email at the app's domain
APP_DOMAIN = "recipebook.ravenstech.com"
DOMAIN_NAME = "RavensTech"
DEVELOPER_NAME = "Jonathan Ballard"
DEVELOPER_ADDRESS = ""
CONTACT_EMAIL = "2ravenstech@gmail.com"
GITHUB_LINK = "https://github.com/JonathanBallard/OliveSteelRaven"
DEVELOPER_LINKEDIN = "https://www.linkedin.com/in/jonathanbal/"
TOS_DATE = "2/4/26"

# Paths 
# & SPLIT TO DEV/PROD
# MEDIA_URL = "/media/"
# MEDIA_ROOT = "/var/www/recipebook/media"
# MEDIA_ROOT = BASE_DIR / "media" #development

#! Everything below that's part of `Template Variables` is currently hardcoded - need update app to pull from here
# Defaults
DEFAULT_USER_IMAGE = "default_user.png"
DEFAULT_RECIPE_IMAGE = "default_recipe.png"

#& =================
#^ SPLIT TO DEV/PROD
#& =================
#HERO_RECIPE_PK = 17 # This recipe is our homepage Hero recipe, otherwise random - SET FOR PRODUCTION
#FEATURED_RECIPE_PKS = [] # These recipes will be shown on the front page, otherwise picked at random

MIN_Q_LEN = 2 # Min Query length for search
MAX_Q_LEN = 64 # Max Query length for search

MAX_TAGS_PER_RECIPE = 3 # Currently hardcoded to 3 elsewhere
MAX_INGREDIENTS_PER_RECIPE = 30 # Not currently enforced
ENABLE_RECIPE_IMAGES = True

# Recipe image size in pixels
HERO_MAX_IMAGE_SIZE = 400
RECIPE_IMAGE_SIZE = 400
#& ==================================================
#^ END Template Variables
#& ==================================================

# Recipe image max size in mb
MAX_IMAGE_SIZE_MB = 1

# Global upload size limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 2097152 # 2mb


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#& =================
#^ SPLIT TO DEV/PROD
#& =================
#SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
#& =================
#^ SPLIT TO DEV/PROD
#& =================
#DEBUG = os.getenv('DEBUG', False) #SPLIT TO DEV/PROD


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "recipebook.ravenstech.com",
    "ravenstech.com",
]


AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # required by allauth
    "django.contrib.sites",
    
    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount", # Social Login
    
    # required for CORS protection
    'corsheaders',
    
    # HTTPS
    'django_extensions',
    
    # My apps
    'accounts',
    'recipes.apps.RecipesConfig',
]

#& ==========================================
#^ Authentication Settings
#& ==========================================

# 1) Users log in using email
ACCOUNT_LOGIN_METHODS = {"email"}  # docs: options include "email" / "username" :contentReference[oaicite:5]{index=5}
ACCOUNT_UNIQUE_EMAIL = True


# 2) Signup form fields (IMPORTANT)
# Make email required with * when you use mandatory verification. :contentReference[oaicite:6]{index=6}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# 3) Email verification is mandatory (blocks login until confirmed) :contentReference[oaicite:7]{index=7}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CHANGE_EMAIL = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # convenience; see docs discussion :contentReference[oaicite:8]{index=8}

# Adds email as username for users going forwards
ACCOUNT_ADAPTER = "accounts.adapters.AccountAdapter"

SITE_ID = 1


#& ==========================================
#^ EMAIL Settings
#& ==========================================
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # For Development
# DEFAULT_FROM_EMAIL = "RecipeBook <no-reply@localhost>" # For Development

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.mailersend.net' # Replace with your SMTP host
EMAIL_PORT = 587 # Common ports are 587 (TLS) or 465 (SSL)

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USERNAME')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True # Use TLS for security
EMAIL_USE_SSL = False
# DEFAULT_FROM_EMAIL = "RecipeBook <noreply@" + str(APP_EMAIL) + ">" # For production
DEFAULT_FROM_EMAIL = "noreply@ravenstech.com"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[RecipeBook] "
#ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

#& ==========================================
#^ CSRF Settings
#& ==========================================
#& =================
#^ SPLIT TO DEV/PROD
#& =================
# CSRF_COOKIE_SECURE = True
# CSRF_TRUSTED_ORIGINS = ["https://yourdomain.com"]



#& ==========================================
#^ Security Settings
#& ==========================================
#& =================
#^ SPLIT TO DEV/PROD
#& =================
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# USE_X_FORWARDED_HOST = True
# SESSION_COOKIE_SECURE = True

# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
#X_FRAME_OPTIONS = "DENY"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'osr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                "common.context_processors.global_settings",
            ],
        },
    },
]

WSGI_APPLICATION = 'osr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#~ ============================================================================================================
#^ Currently settings set for production User/Password. For local development revert to DB_USER and DB_PASSWORD
#~ ============================================================================================================
# DATABASES = {
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.sqlite3',
#     #     'NAME': BASE_DIR / 'db.sqlite3',
#     # }
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'osrdb'),
#         'USER': os.getenv('DB_PROD_USER'),
#         'PASSWORD': os.getenv('DB_PROD_PASSWORD'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),  # Or the host IP if not local
#         'PORT': os.getenv('DB_PORT', ''),           # PostgreSQL default port is 5432. Leaving empty uses the default.
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    # for local development
    "http://localhost:8000", 
    "http://localhost:3000",
    "http://127.0.0.1:9000",
    "http://ravenstech.com",
    "https://recipebook.ravenstech.com",
    "http://recipebook.ravenstech.com",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


#& =================
#^ SPLIT TO DEV/PROD
#& =================
#STATIC_URL = 'static/'
# STATIC_ROOT = "/var/www/recipebook/static" #prod
# STATIC_ROOT = BASE_DIR / "staticfiles" #dev

#& =================
#^ BOTH DEV AND PROD
#& =================
# STATICFILES_DIRS = [
#     BASE_DIR / "static",   # project-wide static folder
# ]

# Login Redirect URL
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "accounts:home"
LOGOUT_REDIRECT_URL = "account_login"
ACCOUNT_LOGOUT_REDIRECT_URL = "account_login"

ACCOUNT_FORMS = {
    "signup": "accounts.forms.SignupForm",
    "login": "accounts.forms.BootstrapLoginForm",
    "add_email": "accounts.forms.BootstrapAddEmailForm",
}

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "accounts:email_confirmed"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "accounts:email_confirmed"

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Keep existing loggers enabled
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': { # This is the "root" logger, handling all messages
            'handlers': ['console'],
            'level': 'DEBUG', # Set to DEBUG to see all messages
            'propagate': True,
        },
        'django': { # Controls Django's internal logging
            'handlers': ['console'],
            'level': 'INFO', # Or DEBUG if you want verbose Django internal logs
            'propagate': False,
        },
    },
}