# Generated by Django 6.0.1 on 2026-01-14 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, default='This is my new recipe.', max_length=500, null=True)),
                ('long_description', models.TextField(blank=True, default='Let me tell you a little about my recipe.', null=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Type the full recipe instructions here. Use new lines for steps if you like.', null=True)),
                ('prep_time_minutes', models.IntegerField()),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category')),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_order', models.IntegerField(default=1)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_text', models.CharField(blank=True, max_length=40, null=True)),
                ('prep_note', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.RESTRICT, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredients',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.tag')),
            ],
            options={
                'db_table': 'recipe_tags',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeTag', to='recipes.tag'),
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recipes.recipe')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_favorites',
                'indexes': [models.Index(fields=['recipe'], name='recipe_favo_recipe__8b3350_idx'), models.Index(fields=['user'], name='recipe_favo_user_id_271a51_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_favorites_pk')],
            },
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe'], name='recipe_ingr_recipe__c09862_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='recipe_ingr_ingredi_1f18f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'line_order'), name='recipe_ingredients_pk'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('line_order__gt', 0)), name='recipe_ingredients_line_order_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='recipe_tags_pk'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['owner'], name='recipes_owner_u_67122b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='recipes_categor_39a7d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('prep_time_minutes__gte', 0)), name='recipes_prep_time_minutes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('user_rating__isnull', True), models.Q(('user_rating__gte', 1), ('user_rating__lte', 5)), _connector='OR'), name='rating_range'),
        ),
    ]
