# Generated by Django 6.0.1 on 2026-01-20 23:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_normalized',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Type the full recipe instructions here. Use new lines for steps if you like.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='long_description',
            field=models.TextField(blank=True, default='Let me tell you a little about my recipe.', help_text='Type a description of your recipe. Talk about its history, origins, or your creative process here.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(blank=True, default='This is my new recipe.', help_text='Type a short description of 300 characters or less. This will show up when people search for your recipe.', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='line_order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name_normalized'], name='idx_ing_norm'),
        ),
    ]
