# Generated by Django 6.0.1 on 2026-01-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_created_at_ingredient_name_normalized_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipe_ingredients_pk',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'line_order'), name='recipe_ingredients_pk'),
        ),
    ]
