# Generated by Django 6.0.1 on 2026-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipeingredient_recipe_ingredients_pk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipe_ingredients_pk',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'line_order'), name='uq_recipe_line_order_pk'),
        ),
    ]
