# Generated by Django 6.0.1 on 2026-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture_url',
            field=models.URLField(default='default.png', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.RecipeTag', to='recipes.tag'),
        ),
    ]
