# Generated by Django 6.0.1 on 2026-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_picture_url_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture_url',
            field=models.URLField(default='default.png', max_length=400),
        ),
    ]
