# Generated by Django 6.0.1 on 2026-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
