# Generated by Django 6.0.1 on 2026-01-24 06:33

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_picture_url_recipe_recipe_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='uq_recipe_line_order_pk',
        ),
        migrations.RemoveIndex(
            model_name='ingredient',
            name='idx_ing_norm',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name_normalized',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('recipe', 'line_order'), name='uq_recipe_line_order_pk'),
        ),
    ]
