# Generated by Django 6.0.1 on 2026-02-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipeingredient_uq_recipe_line_order_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Type a description of your recipe. Talk about its history, origins, or your creative process here.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Type a short description of 300 characters or less. This will show up when people search for your recipe.', max_length=300),
        ),
    ]
