# Generated by Django 6.0.1 on 2026-02-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='defaults/default_recipe.png', null=True, upload_to='recipe_images/'),
        ),
    ]
