# Generated by Django 6.0.1 on 2026-02-05 00:52

from django.db import migrations

def set_default_recipe_image(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")

    DEFAULT_IMAGE = "defaults/default_recipe.png"

    # Only update rows that truly have no image
    Recipe.objects.filter(
        recipe_image__isnull=True
    ).update(recipe_image=DEFAULT_IMAGE)

    Recipe.objects.filter(
        recipe_image=""
    ).update(recipe_image=DEFAULT_IMAGE)


def unset_default_recipe_image(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")

    DEFAULT_IMAGE = "defaults/default_recipe.png"

    # Revert only rows that we set
    Recipe.objects.filter(
        recipe_image=DEFAULT_IMAGE
    ).update(recipe_image=None)


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_recipe_recipe_image"),  # <-- Django will auto-fill this
    ]

    operations = [
        migrations.RunPython(
            set_default_recipe_image,
            reverse_code=unset_default_recipe_image,
        ),
    ]
