# Generated by Django 6.0.1 on 2026-02-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_set_default_recipe_image"),
    ]

    operations = [
        # ---- recipes table ----
        migrations.RunSQL(
            sql="""
            ALTER TABLE recipes
            ALTER COLUMN created_at SET DEFAULT NOW(),
            ALTER COLUMN updated_at SET DEFAULT NOW();
            """,
            reverse_sql="""
            ALTER TABLE recipes
            ALTER COLUMN created_at DROP DEFAULT,
            ALTER COLUMN updated_at DROP DEFAULT;
            """,
        ),

        # ---- ingredients table ----
        migrations.RunSQL(
            sql="""
            ALTER TABLE ingredients
            ALTER COLUMN created_at SET DEFAULT NOW();
            """,
            reverse_sql="""
            ALTER TABLE ingredients
            ALTER COLUMN created_at DROP DEFAULT;
            """,
        ),
    ]