# Generated by Django 6.0.1 on 2026-02-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_add_db_defaults_timestamps"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE recipe_ingredients
            DROP CONSTRAINT IF EXISTS recipe_ingredients_recipe_id_f1590b33_fk_recipes_id;

            ALTER TABLE recipe_ingredients
            ADD CONSTRAINT recipe_ingredients_recipe_id_f1590b33_fk_recipes_id
            FOREIGN KEY (recipe_id)
            REFERENCES recipes(id)
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE recipe_ingredients
            DROP CONSTRAINT IF EXISTS recipe_ingredients_recipe_id_f1590b33_fk_recipes_id;

            ALTER TABLE recipe_ingredients
            ADD CONSTRAINT recipe_ingredients_recipe_id_f1590b33_fk_recipes_id
            FOREIGN KEY (recipe_id)
            REFERENCES recipes(id)
            DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
