# Generated by Django 6.0.1 on 2026-01-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, default='./assets/icons/users/default_user.png', null=True),
        ),
    ]
