# Generated by Django 6.0.1 on 2026-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_tos',
            field=models.BooleanField(default=False),
        ),
    ]
