# Generated by Django 6.0.1 on 2026-02-05 04:00

from django.db import migrations
from django.contrib.auth import get_user_model

def set_agreed_to_tos(apps, schema_editor):
    User = get_user_model()

    User.objects.filter(
        agreed_to_tos=False
    ).update(agreed_to_tos=True)


def unset_agreed_to_tos(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    # Revert only users we touched
    User.objects.filter(
        agreed_to_tos=True
    ).update(agreed_to_tos=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_agreed_to_tos"),  # Django will auto-fill this
    ]

    operations = [
        migrations.RunPython(
            set_agreed_to_tos,
            reverse_code=unset_agreed_to_tos,
        ),
    ]