"""
Django settings for osr project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load Environment variables using python-dotenv library
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#& ==================================================
#^ Available in Templates - Pass to Context Processor
#& ==================================================
APP_NAME = "RecipeBook"
DEVELOPER_NAME = "Jonathan Ballard"
CONTACT_EMAIL = "2ravenstech@gmail.com"

# Paths
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


#! Everything below that's part of `Template Variables` is currently hardcoded - need update app to pull from here
# Defaults
DEFAULT_USER_IMAGE = ""
DEFAULT_RECIPE_IMAGE = ""

MAX_TAGS_PER_RECIPE = 3 # Currently hardcoded to 3
MAX_INGREDIENTS_PER_RECIPE = 30 # Not currently enforced
ENABLE_RECIPE_IMAGES = True

# Recipe image size in pixels
RECIPE_IMAGE_SIZE = 400
#& ==================================================
#^ END Template Variables
#& ==================================================

# Recipe image max size in mb
MAX_IMAGE_SIZE_MB = 1

# Global upload size limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 2097152 # 2mb


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', True)

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    
    'accounts',
    'recipes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
        
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'osrdb'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST', 'localhost'),  # Or the host IP if not local
        'PORT': os.getenv('DB_PORT', ''),           # PostgreSQL default port is 5432. Leaving empty uses the default.
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    # for local development
    "http://localhost:8000", 
    "http://localhost:3000",
    "http://127.0.0.1:9000",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",   # project-wide static folder
]

# Login Redirect URL
LOGIN_REDIRECT_URL = 'home/'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Keep existing loggers enabled
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': { # This is the "root" logger, handling all messages
            'handlers': ['console'],
            'level': 'DEBUG', # Set to DEBUG to see all messages
            'propagate': True,
        },
        'django': { # Controls Django's internal logging
            'handlers': ['console'],
            'level': 'INFO', # Or DEBUG if you want verbose Django internal logs
            'propagate': False,
        },
    },
}